#!/bin/bash

# Set the lockscreen background to the resized Material Design Paper Desktop Background
# Then lock the screen on startup
cp $HOME/Pictures/Lockscreen/l_resized-arch-btw.png $HOME/.cache/i3lock/current/l_resized.png
betterlockscreen -l

# Load virtual surround sound pulseaudio module
#pacmd load-module module-virtual-surround-sink sink_name=vsurround sink_properties=device.description=VirtualSurround hrir=/home/deleuze/.local/share/hrir.wav master=PulseEffects_apps

# Then pick out a new background from my backgrounds folder
# Then set my wallpaper to be that new background
betterlockscreen -u $HOME/Pictures/Backgrounds/
betterlockscreen -w
