############################################################################
## Beets Configuration file.
## ~./config/beets/config.yaml
#############################################################################
 
### Global Options
library: ~/.config/beets/library.blb
directory: ~/Music/
pluginpath: ~/.config/beets/beetsplug
ignore: .AppleDouble ._* *~ .DS_Store
per_disc_numbering: true
threaded: yes

ui:
  color: yes

# Plugins
plugins: [
  convert,
  edit,
  embedart,
  fetchart,
  ftintitle,
  fromfilename,
  lastgenre,
  lyrics,
  missing,
  replaygain,
  rewrite,
  setlister,
  scrub,
  the
]
 
# Import Options
import:
  move: yes
  copy: no
  link: no
  write: yes
  delete: false
  resume: ask
  incremental: false
  quiet_fallback: skip
  timid: false
  group_albums: no
  languages: en
  log: ~/.config/beets/beets-import.log

# Autotagger options
match:
  strong_rec_thresh: 0.05
  preferred:
    contries: ['US','GB|UK','JP']
    media: ['CD','Digital Media|File']
    original_year: yes

# Path options
paths:
  default: %asciify{$albumartist}/%asciify{$album%aunique{}}/%asciify{[$disc - $track] $title}
  singleton: %asciify{$albumartist}/%asciify{$album%aunique{}}/%asciify{[$disc - $track] $title}
  comp: Various Artists/%asciify{$album%aunique{}}/%asciify{[$disc - $track] $title - $artist}
 
### Plugin Options

# Convert plugin options
convert:
  auto: yes
  copy_album_art: yes
  album_art_maxwidth: 500
  embed: yes
  never_convert_lossy_files: yes
  command: /home/deleuze/.bin/gaplessmp3
  extension: mp3

# Embeded album art options
embedart:
  compare_threshold: 80
  maxwidth: 500

# FetchArt options
fetchart:
  minwidth: 500
  sources: coverart albumart wikipedia

# Grab genre info from last.fm
lastgenre:
  auto: yes
  count: 1
  fallback: ''
  force: yes
  prefer_specific: yes
  source: album
  whitelist: no

# Lyrics options
lyrics:
  force: yes
  google_API_key: AIzaSyDNcaUvSnrN2u0EpYaEa4LT05f7379PWHY
 
# Fetch fresh album art for new imports
fetchart:
  sources: coverart itunes amazon albumart
  store_source: yes
  art_source: folder

# Features in the title
ftintitle:
  auto: yes

# MPD options
mpd:
  host: localhost
  port: 6600
  #  password: seekrit

# Normalizing audio decibels
# Gstreamer is a pain, but still the correct backend
replaygain:
  backend: gstreamer
  overwrite: yes

# Rewrite plugin
rewrite:
  artist The Jimi Hendrix Experience: Jimi Hendrix

# Make playlists from setlists
setlister:
  playlist_dir: ~/Music/playlists/setlists
 
# Scrub extra metadata
scrub:
  auto: yes

# WhatLastGenre plugin options
wlg:
  auto: yes
  force: yes
  count: 1
  whitelist: wlg
