############################################################################
## Beets Configuration file.
## ~./config/beets/config.yaml
#############################################################################
 
### Global Options
library: ~/.config/beets/library.blb
directory: ~/Music/
pluginpath: ~/.config/beets/beetsplug
ignore: .AppleDouble ._* *~ .DS_Store
per_disc_numbering: true
threaded: no

ui:
  color: yes

# Plugins
plugins: [
  alternatives,
  edit,
  embedart,
  fetchart,
  ftintitle,
  fromfilename,
  lyrics,
  missing,
  replaygain,
  setlister,
  scrub
]
 
# Import Options
import:
  move: yes
  copy: no
  link: no
  write: yes
  delete: false
  resume: ask
  incremental: false
  quiet_fallback: skip
  timid: true
  group_albums: yes
  languages: en
  log: ~/.config/beets/beets-import.log

# Autotagger options
match:
  strong_rec_thresh: 0.20
  preferred:
    contries: ['US','GB|UK','JP']
    media: ['CD','Digital Media|File']
    original_year: yes

# Path options
paths:
  default: %asciify{$albumartist/$album%aunique{}/$track_$title}
  singleton: %asciify{$artist/$album%aunique{}/$track_$title}
  comp: %asciify{Various_Artists/$album%aunique{}/$track_$title}
 
### Plugin Options

# Use beets to sync with phone
alternatives:
  myplayer:
    directory: ~/mtp/Internal\ shared\ storage/Music
    paths:
      default: %asciify{$albumartist/$album%aunique{}/$track_$title}
      singleton: %asciify{$artist/$album%aunique{}/$track_$title}
      comp: %asciify{Various_Artists/$album%aunique{}/$track_$title}
    formats: mp3
    query: "onplayer:true"
    removable: true

# Embeded album art options
embedart:
  compare_threshold: 80
  maxwidth: 500

# FetchArt options
fetchart:
  minwidth: 500
  sources: coverart albumart wikipedia

# Lyrics options
lyrics:
  force: yes
  google_API_key: AIzaSyDNcaUvSnrN2u0EpYaEa4LT05f7379PWHY
 
# Fetch fresh album art for new imports
fetchart:
  sources: coverart itunes amazon albumart
  store_source: yes
  art_source: folder

# Features in the title
ftintitle:
  auto: yes

# Normalizing audio decibels
# Gstreamer is a pain, but still the correct backend
replaygain:
  backend: gstreamer
  overwrite: yes

# Make playlists from setlists
setlister:
  playlist_dir: ~/Music/playlists/setlists
 
# Scrub extra metadata
scrub:
  auto: yes
