#!/bin/sh
printf "\n"
printf "Cleaning GCC cache... \n"
printf "============================== \n"
printf "\n"
ccache -c
printf "\n"
printf "============================== \n"
printf "\n"
printf "\n"
printf "Cleaning browser profiles... \n"
printf "============================== \n"
printf "\n"
browser-vacuum
printf "\n"
printf "============================== \n"
printf "\n"
printf "\n"
printf "Clean the pacaur package cache \n"
printf "============================== \n"
printf "\n"
pacaur -Sc
printf "\n"
printf "============================== \n"
printf "\n"
printf "\n"
printf "Update the Arch repo & AUR mirrorlist \n"
printf "============================== \n"
printf "\n"
sudo reflector -c US --latest 100 --number 500 --age 12 --sort rate --save /etc/pacman.d/mirrorlist
printf "\n"
printf "============================== \n"
printf "\n"
printf "\n"
